Fix typo in doc
metaplex-foundation/docs pull request #270
Opened 2022-05-25 02:58 UTC by GitHubPang

2022-05-27 02:13 UTC, stranzhay approved these changes

2022-06-14 04:51 UTC, stegaBOB approved these changes

2022-06-14 09:02 UTC, lorisleiva requested changes

2022-06-14 09:02 UTC, lorisleiva commented on docs/token-metadata/specification.md
> +The URI field contains a pointer to the rest of the metadata. This metadata is stored off chain in most cases and the URI is usually a `https:` link to some decentralized storage.
This file no longer exists. Could you please update your branch from `main` so the conflicts are resolved?

2022-06-15 09:48 UTC, lorisleiva approved these changes

2022-06-15 09:48 UTC, merged

2022-06-15 09:48 UTC, lorisleiva commented
Thanks!